import californaia from "./assets/images/companies/california.png";
import atlant from "./assets/images/companies/atlant.png";
import bekins from "./assets/images/companies/bekins.png";
import blackhawk from "./assets/images/companies/blackhawk.png";
import davidson from "./assets/images/companies/davidson.png";
import nearme from "./assets/images/companies/nearme.png";

const companies = [
  {
    id: 1,
    title: "California Movers USA",
    rate: 4.9,
    popular:false,
    featured:false,
    images: californaia,
    adress: "Ontario, Los Angeles, San Diego, San Jose, Oakland, San Francisco",
    telephone: "(415) 579-2747",
  },
  {
    id: 2,
    title: "Atlant Movers",
    rate: 5.0,
    popular:false,
    featured:true,
    images: atlant,
    adress: "Ontario, Los Angeles, San Diego, San Jose, Oakland, San Francisco",
    telephone: "1-916-694-1174",
  },
  {
    id: 3,
    title: "BlackHawk Movers",
    rate: 4.9,
    popular:false,
    featured:false,
    images: blackhawk,
    adress: "Ontario, Los Angeles, San Diego, San Jose, Oakland, San Francisco",
    telephone: "(415) 579-2747",
  },
  {
    id: 4,
    title: "Davidson Movers",
    rate: 4.0,
    popular:true,
    featured:true,
    images: davidson,
    adress: "Ontario, Los Angeles, San Diego, San Jose, Oakland, San Francisco",
    telephone: "(415) 579-2747",
  },
  {
    id: 5,
    title: "Nearme Moving",
    rate: 4.9,
    popular:false,
    featured:false,
    images: nearme,
    adress: "San Diego, San Jose, Oakland, San Francisco",
    telephone: "(628) 333-3698",
  },
  {
    id: 6,
    title: "AMS Bekins",
    rate: 2.9,
    popular:true,
    featured:true,
    images: bekins,
    adress: "San Diego, San Jose, Oakland, San Francisco",
    telephone: "650-729-9804",
  },
  {
    id: 1,
    title: "California Movers USA",
    rate: 4.9,
    popular:false,
    featured:false,
    images: californaia,
    adress: "Ontario, Los Angeles, San Diego, San Jose, Oakland, San Francisco",
    telephone: "(415) 579-2747",
  },
  {
    id: 2,
    title: "Atlant Movers",
    rate: 5.0,
    popular:false,
    featured:true,
    images: atlant,
    adress: "Ontario, Los Angeles, San Diego, San Jose, Oakland, San Francisco",
    telephone: "1-916-694-1174",
  },
  {
    id: 3,
    title: "BlackHawk Movers",
    rate: 4.9,
    popular:false,
    featured:false,
    images: blackhawk,
    adress: "Ontario, Los Angeles, San Diego, San Jose, Oakland, San Francisco",
    telephone: "(415) 579-2747",
  },
  {
    id: 4,
    title: "Davidson Movers",
    rate: 4.0,
    popular:true,
    featured:true,
    images: davidson,
    adress: "Ontario, Los Angeles, San Diego, San Jose, Oakland, San Francisco",
    telephone: "(415) 579-2747",
  },
  {
    id: 5,
    title: "Nearme Moving",
    rate: 4.9,
    popular:false,
    featured:false,
    images: nearme,
    adress: "San Diego, San Jose, Oakland, San Francisco",
    telephone: "(628) 333-3698",
  },
  {
    id: 6,
    title: "AMS Bekins",
    rate: 2.9,
    popular:true,
    featured:true,
    images: bekins,
    adress: "San Diego, San Jose, Oakland, San Francisco",
    telephone: "650-729-9804",
  },
  {
    id: 1,
    title: "California Movers USA",
    rate: 4.9,
    popular:false,
    featured:false,
    images: californaia,
    adress: "Ontario, Los Angeles, San Diego, San Jose, Oakland, San Francisco",
    telephone: "(415) 579-2747",
  },
  {
    id: 2,
    title: "Atlant Movers",
    rate: 5.0,
    popular:false,
    featured:true,
    images: atlant,
    adress: "Ontario, Los Angeles, San Diego, San Jose, Oakland, San Francisco",
    telephone: "1-916-694-1174",
  },
  {
    id: 3,
    title: "BlackHawk Movers",
    rate: 4.9,
    popular:false,
    featured:false,
    images: blackhawk,
    adress: "Ontario, Los Angeles, San Diego, San Jose, Oakland, San Francisco",
    telephone: "(415) 579-2747",
  },
  {
    id: 4,
    title: "Davidson Movers",
    rate: 4.0,
    popular:true,
    featured:true,
    images: davidson,
    adress: "Ontario, Los Angeles, San Diego, San Jose, Oakland, San Francisco",
    telephone: "(415) 579-2747",
  },
  {
    id: 5,
    title: "Nearme Moving",
    rate: 4.9,
    popular:false,
    featured:false,
    images: nearme,
    adress: "San Diego, San Jose, Oakland, San Francisco",
    telephone: "(628) 333-3698",
  },
  {
    id: 6,
    title: "AMS Bekins",
    rate: 2.9,
    popular:true,
    featured:true,
    images: bekins,
    adress: "San Diego, San Jose, Oakland, San Francisco",
    telephone: "650-729-9804",
  },
  {
    id: 1,
    title: "California Movers USA",
    rate: 4.9,
    popular:false,
    featured:false,
    images: californaia,
    adress: "Ontario, Los Angeles, San Diego, San Jose, Oakland, San Francisco",
    telephone: "(415) 579-2747",
  },
  {
    id: 2,
    title: "Atlant Movers",
    rate: 5.0,
    popular:false,
    featured:true,
    images: atlant,
    adress: "Ontario, Los Angeles, San Diego, San Jose, Oakland, San Francisco",
    telephone: "1-916-694-1174",
  },
  {
    id: 3,
    title: "BlackHawk Movers",
    rate: 4.9,
    popular:false,
    featured:false,
    images: blackhawk,
    adress: "Ontario, Los Angeles, San Diego, San Jose, Oakland, San Francisco",
    telephone: "(415) 579-2747",
  },
  {
    id: 4,
    title: "Davidson Movers",
    rate: 4.0,
    popular:true,
    featured:true,
    images: davidson,
    adress: "Ontario, Los Angeles, San Diego, San Jose, Oakland, San Francisco",
    telephone: "(415) 579-2747",
  },
  {
    id: 5,
    title: "Nearme Moving",
    rate: 4.9,
    popular:false,
    featured:false,
    images: nearme,
    adress: "San Diego, San Jose, Oakland, San Francisco",
    telephone: "(628) 333-3698",
  },
  {
    id: 6,
    title: "AMS Bekins",
    rate: 2.9,
    popular:true,
    featured:true,
    images: bekins,
    adress: "San Diego, San Jose, Oakland, San Francisco",
    telephone: "650-729-9804",
  },
  {
    id: 1,
    title: "California Movers USA",
    rate: 4.9,
    popular:false,
    featured:false,
    images: californaia,
    adress: "Ontario, Los Angeles, San Diego, San Jose, Oakland, San Francisco",
    telephone: "(415) 579-2747",
  },
  {
    id: 2,
    title: "Atlant Movers",
    rate: 5.0,
    popular:false,
    featured:true,
    images: atlant,
    adress: "Ontario, Los Angeles, San Diego, San Jose, Oakland, San Francisco",
    telephone: "1-916-694-1174",
  },
  {
    id: 3,
    title: "BlackHawk Movers",
    rate: 4.9,
    popular:false,
    featured:false,
    images: blackhawk,
    adress: "Ontario, Los Angeles, San Diego, San Jose, Oakland, San Francisco",
    telephone: "(415) 579-2747",
  },
  {
    id: 4,
    title: "Davidson Movers",
    rate: 4.0,
    popular:true,
    featured:true,
    images: davidson,
    adress: "Ontario, Los Angeles, San Diego, San Jose, Oakland, San Francisco",
    telephone: "(415) 579-2747",
  },
  {
    id: 5,
    title: "Nearme Moving",
    rate: 4.9,
    popular:false,
    featured:false,
    images: nearme,
    adress: "San Diego, San Jose, Oakland, San Francisco",
    telephone: "(628) 333-3698",
  },
  {
    id: 6,
    title: "AMS Bekins",
    rate: 2.9,
    popular:true,
    featured:true,
    images: bekins,
    adress: "San Diego, San Jose, Oakland, San Francisco",
    telephone: "650-729-9804",
  },
];

export default companies;
